deploymentMode: "SelectorSyncSet"
selectorSyncSet:
  matchExpressions:
  - key: api.openshift.com/product
    operator: In
    values: ["osd", "rosa"]
  - key: hive.openshift.io/version-major-minor-patch
    operator: In
    values: ["4.12", "4.13", "4.14", "4.15", "4.16", "4.17", "4.18"]
  resourceApplyMode: "Sync"
