apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-state-metrics-config
  namespace: hypershift-observability
data:
  custom-resource-state.yaml: |
    spec:
      resources:
        - groupVersionKind:
            group: cluster.x-k8s.io
            version: v1beta1
            kind: Machine
          metricNamePrefix: capi_machine
          labelsFromPath:
            machine_name:
              - metadata
              - name
            exported_namespace:
              - metadata
              - namespace
            _id:
              - metadata
              - labels
              - "cluster.x-k8s.io/cluster-name"
          metrics:
            - name: "info"
              help: "The current state of a machine."
              each:
                type: Info
                info:
                    labelsFromPath:
                      status_phase: [status, phase]
                      ready: [status, conditions, "[type=Ready]", status]
                      healthcheck_succeeded: [status, conditions, "[type=HealthCheckSucceeded]", status]
                      infrastructure_ready: [status, conditions, "[type=InfrastructureReady]", status]
                      node_healthy: [status, conditions, "[type=NodeHealthy]", status]
                      draining_succeeded: [status, conditions, "[type=DrainingSucceeded]", status]