apiVersion: monitoring.rhobs/v1
kind: ServiceMonitor
metadata:
  name: kube-state-metrics
  namespace: hypershift-observability
  labels:
    app.kubernetes.io/name: kube-state-metrics
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-state-metrics
  endpoints:
  - port: http-metrics
    interval: 30s
    path: /metrics