deploymentMode: "SelectorSyncSet"
selectorSyncSet:
  matchExpressions:
  - key: api.openshift.com/product
    operator: In
    values:
    - osd
    - rosa
  - key: api.openshift.com/fedramp
    operator: NotIn
    values:
    - "true"
  resourceApplyMode: "Sync"